### PR TITLE
PDF print cancelled if model path not present

### LINKED ISSUE #94: Save PDF doesn't work
**Describe the bug**
"Save PDF" doesn't create a PDF & puts the program into an unusable state. The blank white screen is what happens after clicking "Save PDF" 3 times.
Screen Shot 2021-06-29 at 12 26 10 PM
 

**Expected behavior**
I expect to be able to save the report as PDF.

**Environment**
- Version: 1.4.0
 - Platform: Desktop
 - OS: MacOS 10.15.7
 
**To Reproduce**
1. Open demo model
2. Click "Save PDF". Nothing happens!
3. Click "Save PDF". Nothing happens!
4. Click "Save PDF". The report disappears and the program is an unusable white page state.

**Any additional context, screenshots, etc**

### LINKED ISSUE #95: "print report" doesn't work
**Describe the bug**
Clicking "Print" on the Demo report results in a red "Report printing failed" modal and nothing happens.

**Expected behavior**
Clicking "Print" on the Demo report should bring up a screen to print the document.

**Environment**
 - Version: 1.4.0
 - Platform: Desktop
 - OS: MacOS 10.15.7
 
**To Reproduce**
1. Open Demo model
2. Click "Report"
2. Click "Print"

**Any additional context, screenshots, etc**

### PR DESCRIPTION
**Pull request by jgadsden**
**Summary**
This is a fix for issue #94 "Save PDF doesn't work" raised by @sherbo
If the demo model is loaded and not saved then the model path is null. This throws an error and we end up with a blank screen. The fix checks for this condition and returns an error message. 

**Description for the changelog**
PDF print cancelled if model path not present

**Other info**
The test for this has been added, but the whole section for PDF print is skipped. I have raised a separate issue for this #99 "PDF print tests are skipped"

### CODE REVIEW

File: test/spec/threatmodels/desktopreport_spec.js [hunk 1]
```diff
@@ -231,6 +231,24 @@ describe('desktopreport controller', function () {
                 expect(done).toHaveBeenCalled();
             });
 
+            xit('should not save the PDF file on null path', function() {
```
Comment (lreading) [inline test/spec/threatmodels/desktopreport_spec.js:234]: Are we intentionally skipping this test?

**Review by lreading — APPROVED** [review]
Looks good!  ~Just a comment on the tests, it looks like it's being skipped and I wanted to make sure that was intended.~ Great work as always, Jon!

File: test/spec/threatmodels/desktopreport_spec.js (hunk 1 above)
Comment (lreading) [reply test/spec/threatmodels/desktopreport_spec.js:234]: Whoops, need to read the linked issues/PRs.  My bad. :sweat_smile:
